In [69]:
import pandas as pd

In [70]:
df = pd.read_csv('../datasets/customer.csv')
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [71]:
# Encoding categorical variables

# In ML we need to encode categorical values. ML models expect numbers and cannot work with categories

# There are 3 ways to encode categorical data
# 1. One hot encoding - used for encoding nominal categorical features.
# 2. Label Encoding - used for target categorical cols
# 3. Ordinal Encoding - used for ordinal categorical features

# NOTE: if your target variable is categorical, use LabelEncoder.
# Label Encoding is only meant to encode target variables. 

# gender --> categorical yes, type nominal
# review --> categorical yes, type ordinal
# education --> categorical yes, type ordinal
# purchased --> categorical yes, type nominal

In [72]:
df = df.iloc[:, 2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [73]:
df['education'].unique()

<StringArray>
['School', 'UG', 'PG']
Length: 3, dtype: str

In [74]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

## train test split

In [75]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2, random_state=42)

X_train.shape, X_test.shape

((40, 2), (10, 2))

In [76]:
X_train.head(), y_train

(     review education
 12     Poor    School
 4   Average        UG
 37  Average        PG
 8   Average        UG
 3      Good        PG,
 12     No
 4      No
 37    Yes
 8      No
 3      No
 6      No
 41    Yes
 46     No
 47    Yes
 15     No
 9     Yes
 16    Yes
 24    Yes
 34     No
 31    Yes
 0      No
 44     No
 27     No
 33    Yes
 5     Yes
 29    Yes
 11    Yes
 36    Yes
 1      No
 21     No
 2      No
 43     No
 35    Yes
 23     No
 40     No
 10    Yes
 22    Yes
 18     No
 49     No
 20    Yes
 7     Yes
 42    Yes
 14    Yes
 28     No
 38     No
 Name: purchased, dtype: str)

In [77]:
# fit on the train set
oe.fit(X_train)

X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

X_train[:5]

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.]])

In [78]:
X_train = pd.DataFrame(X_train, columns=['review','education'])
X_test = pd.DataFrame(X_test, columns=['review','education'])

In [79]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [80]:
# Label Encoder -- which is only used for encoding target categorical variables
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# fit on the training sets
le.fit(y_train)

# transform both training and test sets
y_train = le.transform(y_train)
y_test = le.transform(y_test)

y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [81]:
le.classes_

array(['No', 'Yes'], dtype=object)