In [155]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.tree import DecisionTreeClassifier

In [163]:
df = pd.read_csv('titanic/train.csv')

In [164]:
df = df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'])

In [165]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

# # steps:
# 1. train_test_split
# 2. Impute Age, Embarked
# 3. OneHotEncode Sex, Embarked
# 4. Scale the values
# 5. Feature Selection
# 6. Model Training using DecisionTree

In [166]:
df.shape, df.iloc[:,1:].shape, df[1:].shape

((891, 8), (891, 7), (890, 8))

## Pandas slicing behaviour

In [160]:
df.head(), df.shape

(   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
 0         0       3    male  22.0      1      0   7.2500        S
 1         1       1  female  38.0      1      0  71.2833        C
 2         1       3  female  26.0      0      0   7.9250        S
 3         1       1  female  35.0      1      0  53.1000        S
 4         0       3    male  35.0      0      0   8.0500        S,
 (891, 8))

In [161]:
# df[:,1,:]
# This syntax doesn't work with pandas dataframe but works with numpy 
# We cannot apply slicing along 2 row and col levels parallely. Pandas doesn't allow that.
# we will have to use iloc or loc

df = pd.DataFrame(
    [[10,20,30]],
    columns=['A','B','C']
)

df[0:]  # -> Pandas df
# means
# rows from index position 1 onward

df['A'] # -> Pandas Series
df[['A']] # -> Pandas df
# means select column named 'A' 

# but if we need to apply slicing across both rows and cols
df.iloc[:,1:]

    B   C
0  20  30

## train test split

In [167]:
X_train, X_test, y_train, y_test = train_test_split(
        df.iloc[:,1:],
        df.iloc[:,0],
        test_size=0.2,
        random_state=42
)

In [168]:
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [169]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

## Data Preprocessing

In [170]:
# Instead of chaining multiple ColumnTransformers that rely on numeric positions, use a single ColumnTransformer with nested Pipelines
# using col names avoids al the index-shifting problems
preprocessor = ColumnTransformer(transformers = [
    ('age', SimpleImputer(), ['Age']),
    ('embarked', Pipeline([
        ('imp', SimpleImputer(strategy='most_frequent')),
        ('ohe', OneHotEncoder(sparse_output=False))
    ]), ['Embarked']),
    ('sex', OneHotEncoder(sparse_output=False), ['Sex'])
], remainder='passthrough')

In [171]:
# you can add scaler step in the preprocessor ColumnTransformer as well. 
# ('scaler', MinMaxScaler(), ['Age', 'Fare'])
# This scales only Age and Fare. 
#     But since we wanted to scale all the cols, after one hot encoding the final dataset contains:
# Age, Fare, Sex_male, Embarked_S, Embarked_Q
#         To scale all of them, it's much easier to place
# ('scaler', MinMaxScaler()),
#         after the entire ColumnTransformer in a Pipeline

In [180]:
pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('scaler', MinMaxScaler()),
    ('feature_selection',SelectKBest(score_func=chi2, k=8)),
    ('Model', DecisionTreeClassifier())
])

In [181]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('age', SimpleImputer(),
                                                  ['Age']),
                                                 ('embarked',
                                                  Pipeline(steps=[('imp',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ohe',
                                                                   OneHotEncoder(sparse_output=False))]),
                                                  ['Embarked']),
                                                 ('sex',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['Sex'])])),
                ('scaler', MinMaxScaler()),
                ('feature_selection',
                 SelectKBest(k=8, score_func=<function chi2 at 0x1213cdfe0>)),
                ('Model', DecisionTreeClassifier())])

In [182]:
y_pred = pipe.predict(X_test)

In [183]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7932960893854749

## There is no need to create multiple Column Transformers.

In [93]:
# applying imputation to fill missing values in age and embarked col
tfn1 = ColumnTransformer(transformers = [
    ('age_imp', SimpleImputer(), [2]),
    ('emb_imp', SimpleImputer(strategy='most_frequent'), [6]),
], remainder='passthrough')
tfn1

ColumnTransformer(remainder='passthrough',
                  transformers=[('age_imp', SimpleImputer(), [2]),
                                ('emb_imp',
                                 SimpleImputer(strategy='most_frequent'),
                                 [6])])

In [110]:
tfn1.fit_transform(X_train) 
# ColumnTransformer outputs 
    # 1. transformed cols first
    # 2. then all the passthrough cols

array([[45.5, 'S', 1, ..., 0, 0, 28.5],
       [23.0, 'S', 2, ..., 0, 0, 13.0],
       [32.0, 'S', 3, ..., 0, 0, 7.925],
       ...,
       [41.0, 'S', 3, ..., 2, 0, 14.1083],
       [14.0, 'S', 1, ..., 1, 2, 120.0],
       [21.0, 'S', 1, ..., 0, 1, 77.2875]], shape=(712, 7), dtype=object)

In [94]:
# we are not dropping first col because we will be using DecisionTree. 
# droppping col has no impact on tree based algos. It only affects linear models

# applying OHE on sex and embarked cols
tfn2 = ColumnTransformer(transformers = [
    ('sex_ohe', OneHotEncoder(sparse_output=False), [1]),
    ('emb_ohe', OneHotEncoder(sparse_output=False), [6]),
], remainder='passthrough')
tfn2

ColumnTransformer(remainder='passthrough',
                  transformers=[('sex_ohe', OneHotEncoder(sparse_output=False),
                                 [1]),
                                ('emb_ohe', OneHotEncoder(sparse_output=False),
                                 [6])])

In [95]:
# MinMaxScaler` doesn't reduce the effect of outliers, but it linearly
# scales them down into a fixed range, where the largest occurring data point
# corresponds to the maximum value and the smallest one corresponds to the
# minimum value

# scaling values across all the cols
tfn3 = ColumnTransformer(transformers = [
    ('scale', MinMaxScaler(), slice(0,10)),
], remainder='passthrough')
tfn3

ColumnTransformer(remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(), slice(0, 10, None))])

In [96]:
# feature selection
tfn4 = SelectKBest(score_func=chi2, k=8)
tfn4

SelectKBest(k=8, score_func=<function chi2 at 0x1213cdfe0>)

In [97]:
tfn5 = DecisionTreeClassifier()
tfn5

DecisionTreeClassifier()

## creating a pipeline

In [98]:
pipe = Pipeline([
    ('tfn1', tfn1),
    ('tfn2', tfn2),
    ('tfn3', tfn3),
    ('tfn4', tfn4),
    ('tfn5', tfn5)
])

## Pipeline vs make_pipeline

Pipeline requires naming of steps, make_pipeline does not.
(Same applies to ColumnTransformer vs make_column_transformer)

In [78]:
# Alternate syntax
pipe = make_pipeline(tfn1, tfn2, tfn3, tfn4, tfn5)

In [101]:
pipe

array(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'],
      dtype=object)

In [125]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('age', SimpleImputer(), ['Age']),
                                ('embarked',
                                 Pipeline(steps=[('imp',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('ohe',
                                                  OneHotEncoder(sparse_output=False))]),
                                 ['Embarked']),
                                ('sex', OneHotEncoder(sparse_output=False),
                                 ['Sex'])])

In [124]:
# mean value of age
preprocessor.named_transformers_['age'].statistics_

array([29.49884615])

In [126]:
preprocessor.named_transformers_

{'age': SimpleImputer(),
 'embarked': Pipeline(steps=[('imp', SimpleImputer(strategy='most_frequent')),
                 ('ohe', OneHotEncoder(sparse_output=False))]),
 'sex': OneHotEncoder(sparse_output=False),
 'remainder': FunctionTransformer(accept_sparse=True, check_inverse=False,
                     feature_names_out='one-to-one')}

In [130]:
# most frequent Embarked value
preprocessor.named_transformers_['embarked'].named_steps['imp'].statistics_

array(['S'], dtype=object)

In [138]:
# this is how I can debubg each step of the pipeline
preprocessor.transformers_[1][1].named_steps['ohe'].categories_

[array(['C', 'Q', 'S'], dtype=object)]

In [143]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

In [144]:
# Train model
clf.fit(X_train_transformed, y_train)

NameError: name 'clf' is not defined

## Explore the Pipeline

In [91]:
from sklearn import set_config
set_config(display='diagram')